#HTTP文件用于测试
GET http://localhost:8002/business/hello
Accept: application/json

###

#HTTP文件用于测试
GET http://localhost:8000/business/hello
Accept: application/json

###


GET http://47.98.225.182:80/business/hello
Accept: application/json