
#HTTP文件用于测试
#gtr
GET http://localhost:8000/member/member/count
Accept: application/json

###

#ptrp
POST http://localhost:8000/member/member/register
Content-Type: application/json

{
  "mobile":"12305448760"
}


###


#ptrp
POST http://localhost:8000/member/member/sendCode
Content-Type: application/json

{
  "mobile":"12305448760"
}

###

#ptrp
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
"mobile":"1",
"code":"8888"
}

> {%
    client.log(JSON.stringify(response.body));
    client.log(response.body.result.token);
    client.global.set("token",response.body.result.token);
%}

###