#HTTP文件用于测试
GET http://localhost:8001/member/hello
Accept: application/json

###

#HTTP文件用于测试
GET http://localhost:8000/member/hello
Accept: application/json

###

GET http://47.98.225.182:80/member/hello
Accept: application/json