server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
#          使用nacos前
#          uri: http://127.0.0.1:8001
#        使用nacos后 lb后面跟的是服务 application/name的名字
#          而且gateway服务业要连入到nacos
#          使用lb 得在pom加入spring-cloud-starter-loadbalancer
          uri: lb://member-service

        - id: business
          predicates:
            - Path=/business/**
#          uri: http://127.0.0.1:8002
          uri: lb://business-service

        - id: batch
          predicates:
            - Path=/batch/**
#          uri: http://127.0.0.1:8003
          uri: lb://batch-service
#          解决跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600




