server:
  port: 8002
#  context-path 项目API前缀 加了要放访问的话 必须要加上这个前缀
  servlet:
    context-path: "/business"



spring:
  datasource:
    username: train_business
    password: KEY!moling!6
    url: jdbc:mysql://rm-cn-uax39xxd10011clo.rwlb.rds.aliyuncs.com/train-business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  用于外键
  application:
    name: business-service

mybatis:
  #让mybatis知道xml文件在哪
  mapper-locations: classpath:/mapper/**/*.xml
  #设置一级缓存是否开启
#  local-cache-scope有session/statement(sql)
#local-cache-scope 什么时候情况缓存，session 绘画结束后清空 ，statement执行完sql就会情况
#  什么时候是session，使用了Transactional 事务注释
  configuration:
    local-cache-scope: statement

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql


#log4j使用时候 打印sql信息
logging:
  level:
    com:
      jktickets:
        mapper:
          trace
