server:
  port: 8003
#  context-path 项目API前缀 加了要放访问的话 必须要加上这个前缀
  servlet:
    context-path: "/batch"



spring:
  datasource:
    username: train_batch
    password: KEY!moling!6
    url: jdbc:mysql://rm-cn-uax39xxd10011clo.rwlb.rds.aliyuncs.com/train-batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  用于外键
  application:
    name: batch-service

mybatis:
  #让mybatis知道xml文件在哪
  mapper-locations: classpath:/mapper/**/*.xml

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql


#log4j使用时候 打印sql信息
logging:
  level:
    com:
      jktickets:
        mapper:
          trace
